### ISSUE TITLE
demo2.html refers to undefined styles.css?

### ISSUE THREAD

**Issue by jfly** [cubing/icons#1]
https://github.com/cubing/icons/blob/master/demo2.html#L9

**Comment by FatBoyXPC** [comment]
This is due to renaming the fine to cubing-icons.CSS. I'll update it
tonight.

**Comment by FatBoyXPC** [comment]
Bah, I totally forgot to put in the commit message that I fixed this. https://github.com/cubing/icons/commit/5d13abe7535bee4c78fe4950860715b73cf143f6
