### ISSUE TITLE
Add Team Blindfolded icon

### ISSUE THREAD

**Issue by lgarron** [cubing/icons#100]
Probably `333-team-bf` to keep consistency with `333bf`.

(Note that "blindfolded team solving" generally refers to a different event, so `333bf-team` is not a good choice.)

**Comment by dmint789** [comment]
I also really want this one, although I use 333tbf to make it more similar to 333mbf. But I can always switch to another convention, I'm not too picky.

Also, I would love to have a second version of this icon that has an X through it, same as Multi-Blind Old Style. I refer to team blind with inspection as Team-Blind Old Style (333tbfo), and without inspection as Team-Blind (333tbf) on [cubingcontests.com](https://cubingcontests.com).

**Comment by dmint789** [comment]
This can be closed now

**Comment by jfly** [comment]
Thanks, @dmint789!
