### ISSUE TITLE
BLD Team Relay Icons

### ISSUE THREAD

**Issue by dmint789** [cubing/icons#105]
I would love to have icons for these events:
3x3 Blindfolded 2/3/4/8-man Relay (333bf2mr, 333bf3mr, 333bf4mr, 333bf8mr)
3x3 + OH + BLD Team Relay (333ohbfr)
3x3 Team Factory (333tf)

I want to use them here: https://cubingcontests.com/rankings/333bf2mr/single

**Comment by dmint789** [comment]
Well, team factory is not a blindfolded relay, but I don't think it made sense to open another issue just for that. If no one has capacity to work on these, I can try to make them myself and open a PR, I'd just need some tips for how it's done in this repo.

**Comment by jfly** [comment]
@dmint789, adding a new icon is pretty straightforward, just open a PR adding one or more svg file(s) in the right place such as `svgs/unofficial/333tf.svg`. Here's an example PR: https://github.com/cubing/icons/pull/82/

It's easiest to start by copying an existing SVG and editing it, just so you get the size right.

**Comment by dmint789** [comment]
@jfly I see, thanks for the info! I have done some graphical stuff in gimp before, so I doubt this will be hard. I might also create the icons for team blind and team blind old style.

Could you please help me with ideas for what these icons could look like? There is an existing design for a team-blind icon [here](https://funcubing.org/competitions/rankings) (it's the bottom-most icon on the left, with the two circles and a blindfold). Although I'm not sure this is a good representation of Team-Blind, what do you think?

For the team relays we could just have a number next to  a blindfold, no? I doubt people would think it refers to the number of layers, since that is represented using squares, not numbers.

**Comment by jfly** [comment]
> I have done some graphical stuff in gimp before, so I doubt this will be hard

I've only ever used gimp for rasterized stuff, I'd suggest using inkscape to deal with svgs.

I'm not generally very clever on design stuff, I'll try to answer your other questions, but also feel free to just put up a PR and we can discuss over there.

> Although I'm not sure this is a good representation of Team-Blind, what do you think?
> ![image](https://github.com/cubing/icons/assets/277474/6417768a-680b-40f8-a497-20d80baccc1b)

Ha! That is a very cute icon, and I like how it reuses our blindfold lima bean, and almost looks like 2 stick figures. I like it.

> For the team relays we could just have a number next to a blindfold, no? I doubt people would think it refers to the number of layers, since that is represented using squares, not numbers.

Up until now, we've avoided using numbers in the icons. Riffing off of your team blindfold icon, what if we started saying circles refer to human beings? An icon for a 2-person relay should have 2 circles in it, a 3-person relay should have 3 circles, etc.

**Comment by dmint789** [comment]
Okay, I guess we can use that same icon for team blind, although how would we differentiate between team blind and 2 man bld relay? Maybe the latter can be 3bld (3 squares + blindfold on the right) with two circles stacked vertically on the left, and then 3, 4 and 8-man would be 3, 4 and 8 circles respectively (8-man can have two columns with 4 circles each).

**Comment by dmint789** [comment]
Here's what I had in mind for 2-man BLD relay, going with your circle = human idea. I had to squish the blindfold horizontally a little bit to make everything fit nicely. What do you think?

![333bf2mr](https://github.com/cubing/icons/assets/53250435/5c898937-ea08-4b5e-8a64-fe44d64d2d8f)

**Comment by jfly** [comment]
> although how would we differentiate between team blind and 2 man bld relay

I don't have a good answer to this. It does make me wonder if we're pushing boundaries of how much information can reasonably be packed into a small square icon.

**Comment by dmint789** [comment]
> > although how would we differentiate between team blind and 2 man bld relay
> 
> I don't have a good answer to this. It does make me wonder if we're pushing boundaries of how much information can reasonably be packed into a small square icon.

Well, do you think the one I sent above is okay? I actually like it personally. I can make the other three too and then you can decide.

**Comment by dmint789** [comment]
@jfly I have made all of the bld relay icons in PR #107. It includes a preview too. Please review.
