### ISSUE TITLE
Should big cubes have numbers in them?

### ISSUE THREAD

**Issue by jfly** [cubing/icons#13]
Has this been discussed before? They are kind of hard to differentiate right now. @lgarron, I feel like you'd have an opinion here.

**Comment by AlexMaass** [comment]
here is what I came up with, the 7 is a bit off though
https://i.gyazo.com/e1ecd122fe883c391b5d258b043afa6b.png

**Comment by AlexMaass** [comment]
Here's what I came up with; the 7 is a bit off though.
https://i.gyazo.com/e1ecd122fe883c391b5d258b043afa6b.png

Individual SVG files here:
http://svgshare.com/i/Tr.svg
http://svgshare.com/i/VN.svg
http://svgshare.com/i/Ts.svg
http://svgshare.com/i/TG.svg

**Comment by keemy** [comment]
This is pretty cool. I don't think the 4 or 5 tho is needed and yeh 7 looks
a bit off. Also for 6 how does it look using the negative space? (it's sort
of awk right now since using the blackspace the top of the 6 is bigger than
the bottom)

**Comment by AlexMaass** [comment]
eh I see no harm in adding them in, but we'll see. 
what do you mean the negative space? you want me to invert the image colors?

**Comment by keemy** [comment]
yeah I was thinking to the effect of (but done properly) 
![image](https://cloud.githubusercontent.com/assets/626229/21633817/5f575e10-d207-11e6-8e0d-2a903da143a2.png) . But actually this looks kind of bad so nvm.

maybe instead something just off centered would work better for the 6 and 7 like (look very zoomed out)

![image](https://cloud.githubusercontent.com/assets/626229/21633904/f0fb43c2-d207-11e6-8e67-2b99e4a75dbb.png)

![image](https://cloud.githubusercontent.com/assets/626229/21633940/35cd5a12-d208-11e6-9248-adef595a6feb.png)

**Comment by AlexMaass** [comment]
ooo those all look cool
the negative thing seems like a cool idea but it doesn't seem to look that good
i personally wouldn't prefer the 7 and the 6 to be like that in the corner (too small) but thats just my preference

figured out how to make the 7 not look off, the latter is meh though; its inconsistent compared to 4-6

https://i.gyazo.com/33a77fa1f4c667f84dba48eafa0eb33c.png this seems like a simple fix for 7
I was also thinking of a diagonal thing like this but i cant seem to "latch" onto the corners of the squares to connect the lines required for it accurately https://i.gyazo.com/dae2153a2692f2209b311ed56fabe3de.png

@jfly would you be willing to add in the icons i've proposed (but with this for 7: https://i.gyazo.com/33a77fa1f4c667f84dba48eafa0eb33c.png )

I would need to add do 4bld and 5bld but those should be easy

**Comment by keemy** [comment]
Yeah that 7 looks better. Still overall for 4-5 I don't really see the point and would prefer to avoid them (if enough people think otherwise then could merge them assuming there were suitable 4bld and 5bld changes) and for 6 it's kind of too lopsided. 

If other people have opinions would be good to hear.

**Comment by AlexMaass** [comment]
yeah the 6 looks a bit unnatural; I tried this: https://i.gyazo.com/d49ce64ffabc4396570bf946799f7976.png
looks worse imo and doesn't seem to fix it lol, so I guess we'll keep the 6 as it is 

also I believe there is a point to having the 4-5, on the registration list on the wca for example, the icons are small so it would be quite beneficial to make them have numbers (see what 4-7 look on registration lists on wca website right now) https://i.gyazo.com/1d66e4cf420d9175c2fe44a7fa8f2714.png

anyways, I am hoping these changes I have proposed can be added, let me know what you guys think

**Comment by keemy** [comment]
Wait I'm not sure where it looks like that they are much larger for me when I check registration pages. Do you use <100% scale on your web browser?

**Comment by AlexMaass** [comment]
no i use 100 percent scale on my web browser
this is the webpage
https://www.worldcubeassociation.org/competitions/ImaginaliaOpen2017/registrations
and this is what it looks like for me on my browser
https://i.gyazo.com/1a6e72b07fb5693fd1fb2e578d2e10ef.png

**Comment by jfly** [comment]
> anyways, I am hoping these changes I have proposed can be added, let me know what you guys think

There have been a lot of proposals in this thread. I've asked @AlexMaass to write up a google doc summarizing all the ideas. After that, I think @FatBoyXPC, @keemy, and @jfly (that's me!) will vote on them (of course, agreeing to do something isn't the same thing as actually doing it, but we'll burn that bridge when we get to it)

**Comment by AlexMaass** [comment]
https://docs.google.com/document/d/1Hxx_fu9MJr5k4ESqIACPhUI_fzXCFhBt-iFrh6KlSKY/edit?usp=sharing
nothing like having a comp and being sick with a stomach flu for delaying this : p

**Comment by lgarron** [comment]
So, I think the numbers covering the squares are a cute idea, but they are unreadable.

I'm imagining we only get one tint color, but can we reduce the squares to small dots?

**Comment by lgarron** [comment]
Also, I suggest making a "European" 7 with a horizontal stroke for maximum clarity.

**Comment by jfly** [comment]
> I'm imagining we only get one tint color, but can we reduce the individual squares to small dots?

Yeah, we're targeting a font, so it has to be true black and white. Can you provide quick and dirty mockups of any ideas you have?

**Comment by lgarron** [comment]
![4](https://cloud.githubusercontent.com/assets/248078/21830627/e2bbd182-d752-11e6-8e6e-1e368603425d.png)


![5](https://cloud.githubusercontent.com/assets/248078/21830628/e2bcb250-d752-11e6-965a-6cbd22c6b9ea.png)


![6](https://cloud.githubusercontent.com/assets/248078/21830630/e2bf1ee6-d752-11e6-87a3-0489ffcc5ac3.png)


![7](https://cloud.githubusercontent.com/assets/248078/21830629/e2bd69e8-d752-11e6-831b-312f1ce57105.png)

**Comment by keemy** [comment]
@lgarron but these aren't cubes, and ticks on 7s are terrible.

**Comment by jbcm627** [comment]
@lgarron, I like that they are readable at 14px wide :)

I do like ticks on 7's. Other no-tick styles are ok too though:
![sevens](https://cloud.githubusercontent.com/assets/964048/21831693/a8d8aabe-d773-11e6-805f-6141932d018d.png)
![big7](https://cloud.githubusercontent.com/assets/964048/21831657/617c5c88-d773-11e6-9042-6c0385cfe186.png)

**Comment by AlexMaass** [comment]
I have to agree with keemy, these represent cubes, so it is logical to have squares in it instead of circles. I strongly disapprove of the usage of circles.
Also, I agree that ticks look bad on 7s, but I'm guessing Europeans might be used to ticked 7s, maybe we could compromise and have smaller tricks?

And for what jbcm627 has suggested, I think that looks great!

**Comment by AlexMaass** [comment]
@keemy could you update the svg files I suggested with smaller squares? unfortunately my SVG skills are too limited to do it accurately enough for final usage. I can give the updated 7 SVG though in a bit, I'll update the doc with it which has the rest of the files.

**Comment by lgarron** [comment]
In case you want, the files are at https://drive.google.com/open?id=0B6FmQe6bc6yVQTVDbTJRWjBzeEk

**Comment by lgarron** [comment]
Some variations:

`circles-12-lines-16-square`
![all](https://cloud.githubusercontent.com/assets/248078/21833165/174ceb5e-d765-11e6-91d4-599a12aa5b37.png)


`circles-12-lines-24-square`
![all](https://cloud.githubusercontent.com/assets/248078/21833160/12898fdc-d765-11e6-9305-b942de3e3f3a.png)


`circles-16-lines-16-rounded`
![all](https://cloud.githubusercontent.com/assets/248078/21833155/0f840f2e-d765-11e6-9d50-bb69f7a24a4a.png)


`circles-16-lines-16-square`
![all](https://cloud.githubusercontent.com/assets/248078/21833153/0beadf6e-d765-11e6-8cc1-ad43b6d298fe.png)


`circles-16-lines-24-square`
![all](https://cloud.githubusercontent.com/assets/248078/21833151/08a9489a-d765-11e6-8f21-27eea45bb64c.png)


`squares-16-lines-16-square`
![all](https://cloud.githubusercontent.com/assets/248078/21833149/05163d6e-d765-11e6-84ad-2ac6743000e9.png)

**Comment by AlexMaass** [comment]
Yeah, squares-12-lines-20-square without the dashed 7 looks better and more readable in my opinion!
image of what I'm referring to: 
![42c1d0b49a59e81ae4a2502f3548c624](https://cloud.githubusercontent.com/assets/11395942/21870815/49a8577e-d82c-11e6-9a80-66538b468388.png)
(the subfolder of the folder for this in which Lucas linked is here: https://drive.google.com/drive/u/0/folders/0B6FmQe6bc6yVUFdwamVfVWQtcWs)
I think these would be great!

**Comment by jfly** [comment]
I vote for the icons @AlexMaass just posted [here](https://github.com/cubing/icons/issues/13#issuecomment-272029816).

@lgarron, @keemy, @FatBoyXPC: what say you?

**Comment by lgarron** [comment]
I still prefer the European 7 for the most-clear, most-connected option. :-)

But if we want the broken 7, what about these options?

<img width="107" alt="screen shot 2017-01-11 at 18 12 42" src="https://cloud.githubusercontent.com/assets/248078/21874447/cad0e0ee-d829-11e6-91e9-91d021ee5583.png">
<img width="114" alt="screen shot 2017-01-11 at 18 13 36" src="https://cloud.githubusercontent.com/assets/248078/21874448/cad2f532-d829-11e6-8416-7b2248b726d4.png">

**Comment by lgarron** [comment]
Also note that bigger cubes get pretty thin. Perhaps we should use squares-12-lines-24-square for those.

![screen shot 2017-01-12 at 16 31 42 1](https://cloud.githubusercontent.com/assets/248078/21913941/c38810c6-d8e4-11e6-8343-96b064585194.png)

**Comment by keemy** [comment]
what about trying double wide on the 7 ?

**Comment by lgarron** [comment]
Also, heres a thicker 7:

![thicker-7](https://cloud.githubusercontent.com/assets/248078/22443699/b4793fe2-e6f4-11e6-90a1-3c1985f57e75.png)

**Comment by AlexMaass** [comment]
okay please no, this looks quite bad, though this was still worth trying out to see how it looked

**Comment by dmint789** [comment]
So is this issue stale now?

**Comment by jfly** [comment]
I agree, I think we can close this. It's an interesting piece of history if someone does want to revisit this, but I'm not losing any sleep with how things are right now.
