### ISSUE TITLE
jfly's own Personal Access Token is being used for this repository

### ISSUE THREAD

**Issue by jfly** [cubing/icons#45]
See: https://github.com/cubing/icons/blob/c31d34a7b0692c5a199d716e3c8c9bfe611766f0/.travis.yml#L18

I would like to get this off of my personal GitHub account in favor of something tied to the cubing organization.

The way we handled this for https://github.com/thewca/ was to create a new GitHub account and add it as a member of our `thewca` organization: https://github.com/orgs/thewca/people/thewca-bot. There are some pains associated with this:

1. Creating a new github account requires an associated email address.
2. We need to share the credentials to this new github account and email address with members of `thewca` organization, which is a pain. We already have some infrastructure for storing secrets for `thewca`, but AFAIK, we don't have any such infrastructure for `cubing`.

@lgarron, what do you think would be a good way to move forward on this? Does GitHub provide any sort of "access tokens associated with an organization"? That's basically all we need here.

**Comment by lgarron** [comment]
Idunno; I'll look into it.

**Comment by jfly** [comment]
After some research, I discovered that deploy keys seem to be an ok fix for this: https://github.com/cubing/icons/pull/58.

In a private conversation, @lgarron suggested switching to GitHub actions:

> You just need to push to `gh-pages`, right?
> The easiest is to have an Actions workflow that commits to that branch.
> Actions are about as easy to use as Travis.
> https://github.com/cubing/cubing.js/blob/main/.github/workflows/node.yml
> And you can run git commands there.

That all sounds pretty nice, but I wasn't sure it would be less effort to figure out than continuing to hack on our travis setup.
