### ISSUE TITLE
Deploy to npm

### ISSUE THREAD

**Issue by UnsolvedCypher** [cubing/icons#60]
This would be a nice package to have on npm so that it can be installed as a Node dependency rather than having to clone the repo or direct npm to install from Github.

**Comment by FatBoyXPC** [comment]
Feel free to make it happen!

**Comment by UnsolvedCypher** [comment]
Ok! I imagine this should be published under an org called cubing? I can create this organization if that is agreeable. Is there anyone that should be added to that org?

**Comment by lgarron** [comment]
> Ok! I imagine this should be published under an org called cubing?

We already have one! I'd like to be careful what to put on there until it's ready, but I'd be happy to add `@cubing/icons` and give a few folks permissions once we have a package ready.
