### ISSUE TITLE
Deprecated events missing

### ISSUE THREAD

**Issue by jfly** [cubing/icons#8]
There are no icons for `magic`, `mmagic`, and `333mbo`. I'm starting to use this on [cubing/worldcubeassociation.org](https://github.com/cubing/worldcubeassociation.org), so it would be nice to not have to hack around this over there. Even some boring text would be fine.

**Comment by jfly** [comment]
Workaround here: https://github.com/jfly/worldcubeassociation.org/blob/master/WcaOnRails/app/assets/stylesheets/competitions.scss#L1

**Comment by keemy** [comment]
still need one for old multibld but magics exist now
