### ISSUE TITLE
Add `@cubing/icons` to cdn.cubing.net

### ISSUE THREAD

**Issue by lgarron** [cubing/icons#94]
https://cdn.cubing.net/ is designed to support serving more than just JS: https://github.com/cubing/cdn.cubing.net/tree/main/src/static

We need to figure out:

1. which builds to serve, and
2. under which URLs (e.g. https://cdn.cubing.net/css/@cubing/icons vs. https://cdn.cubing.net/symbols/@cubing/icons/css )

Once that's all in place, I'd like to change the website to recommend using only the following two recommendations:

1. the CDN, or
2. The `npm` module.

We don't have to *break* use of locally vendored files, but these defaults would bring `icons` in line with other github.com/cubing projects, and give us a consistent set of "supported" ways to use the projects. (In particular, it also allows us to deprioritize issues reported with *unsupported* ways, which is valuable given everyone's limited volunteer time.)

**Comment by lgarron** [comment]
> > it also allows us to deprioritize issues reported with unsupported ways, which is valuable given everyone's limited volunteer time
> 
> I'm not opposed to the high level plan, but I don't think we've actually experienced any pain supporting locally vendored files.

Yeah, I won't dispute that. But I do want to make this consistent across projects, as much as possible. Consider the following:

- Suppose we find out that one of the numerous security vulns in our toolchains actually *does* affect the security of the build. Within a matter of minutes to hours, we can:
  - Update the CDN
  - Mark the published versions on `npm` as insecure or deprecated, and offer new ones.
- Pedagogical consistency. If someone asks "why can I easily find a file for `@cubing/icons` that I can throw in my project, but not `cubing.js`?", there is a good answer. But rather than having to explain the difference, I'd rather offer "paved paths" that don't require people to retool their projects once they've started using their first `github.com/cubing` projects.

**Comment by lgarron** [comment]
I have this up at https://cdn.cubing.net/css/@cubing/icons
I'll let it bake at least a few days.

**Comment by lgarron** [comment]
This is in place, and I've been using it to great success. Closing this out — I'll leave followups to other issues and PRs.

**Comment by jfly** [comment]
@lgarron did you mean to close this issue?

**Comment by lgarron** [comment]
Ah, yes, thanks!
